apiVersion: v1
kind: Service
metadata:
  name: hdx-portal-admin-frontend
spec:
  selector:
    app: hdx-portal-admin-frontend
  type: {{.Values.ServiceType}}
  ports:
    - port: 8080
      targetPort: 8080
