# Default values for matilda-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2
imagetag: "v0.3.1"
imagename: "docker-local/matilda-backend"
settingsModule: "mlopsapi.settings.development-tanzu"
kubeconfigpath: "/kube/kube-config-tanzu"
repositoryhost: "nexus.mlops.matilda-mzc.com"
pvname: "pvc-b14dc29c-e172-49e4-973d-78c9e109d86f"
