# Default values for matilda-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
imagetag: "7c2185"
imagename: "docker-local/matilda-asset-backend"
settingsModule: "config.settings.hdx_qa"
kubeconfigpath: "/kube/kube-config-hdx"
repositoryhost: "qa-nexus.hdx.matilda-mzc.com"
pvname: "project-pv"
