# Default values for matilda-backend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 3
imagetag: "483b71"
imagename: "docker-local/matilda-asset-backend"
settingsModule: "config.settings.dev_cluster"
kubeconfigpath: "/kube/kube-config-gpu"
repositoryhost: "15.164.12.54:5000"
pvname: "project-pv"
