apiVersion: apps/v1
kind: Deployment
metadata:
  name: matilda-background-task
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: matilda-background-task
  template:
    metadata:
      labels:
        app: matilda-background-task
    spec:
      containers:
      - args:
        - manage.py
        - runserver
        - 0.0.0.0:8000
        - --settings
        - {{.Values.settingsModule}}
        - --noreload
        command:
        - python3
        env:
        - name: KUBECONFIG
          value: {{.Values.kubeconfigpath}}
        image: {{.Values.repositoryhost}}/{{.Values.imagename}}:{{.Values.imagetag}}
        name: matilda-background-task
        ports:
        - containerPort: 8000
          protocol: TCP
      imagePullSecrets:
      - name: {{.Values.secretName}}
